displayName=RS-Flipper
author=Ramon
description=GE flipping assistant: live buy/sell suggestions, automatic profit tracking and real-time dump alerts
tags=grand exchange,flipping,merching,money making,ge,trading
version=
plugins=de.rsflipper.RSFlipperPlugin
build=standard
